name: Native (Custom Marian) MacOS

on:
  push:
    branches: [ main, ci-sandbox ]
  pull_request:
    branches: [ main, ci-sandbox ]

jobs:
  build-macos:
    name: MacOS
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake ..

    - name: Compile
      working-directory: build
      run: make -j2

    - name: Print versions
      working-directory: build
      run: |
        ./app/bergamot-translator-app --version
