name: Windows

on:
  push:
    branches: [ main, ci-sandbox ]
  pull_request:
    branches: [ '**' ]

env:
  MKL_URL: "https://romang.blob.core.windows.net/mariandev/ci/mkl-2020.1-windows-static.zip"
  CCACHE_BASEDIR: "${{ github.workspace }}"
  CCACHE_DIR: "${{ github.workspace }}\\ccache"
  CCACHE_COMPILERCHECK: content
  CCACHE_COMPRESS: 'true'
  CCACHE_COMPRESSLEVEL: 9
  CCACHE_MAXSIZE: 200M
  ccache_version: '4.5'

jobs:
  build-windows:
    strategy:
      matrix:
        include:
          # Windows CPU-only build
          - name: "Windows CPU-only"
            identifier: "windows-x64"

    runs-on: windows-2019
    name: ${{ matrix.name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive


    - name: Download ccache
      shell: cmake -P {0}
      run: |
        set(ccache_url "https://github.com/cristianadam/ccache/releases/download/v${{ env.ccache_version }}/${{ runner.os }}.tar.xz")
        file(DOWNLOAD "${ccache_url}" ./ccache.tar.xz SHOW_PROGRESS)
        execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./ccache.tar.xz)
        if(ret AND NOT ret EQUAL 0)
          message( FATAL_ERROR "Bad exit status")
        endif()

    - name: Generate ccache_vars for ccache based on machine
      shell: cmake -P {0}
      id: ccache_vars
      run: |-
        string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
        message("::set-output name=timestamp::${current_date}")
        message("::set-output name=hash::${{ env.ccache_compilercheck }}")

    - name: Cache-op for build-cache through ccache
      uses: actions/cache@v2
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-${{ matrix.identifier }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
        restore-keys: |-
          ccache-${{ matrix.identifier }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}
          ccache-${{ matrix.identifier }}-${{ steps.ccache_vars.outputs.hash }}
          ccache-${{ matrix.identifier }}

    - name: ccache prolog
      run: |-
        ${{github.workspace}}\ccache.exe -sv # Print current cache stats
        ${{github.workspace}}\ccache.exe -z # Print current cache stats

    - name: Download MKL
      run: |
        # Wget retries downloading files and is faster than Invoke-WebRequest
        C:\msys64\usr\bin\wget.exe -nv ${{ env.MKL_URL }} -O mkl.zip
        Expand-Archive -Force mkl.zip ${{ github.workspace }}\mkl
        # Set MKLROOT environment variable so that CMake can find MKL
        echo "MKLROOT=${{ github.workspace }}\mkl" | Out-File -FilePath $env:GITHUB_ENV  -Encoding utf8 -Append
      shell: powershell

    - name: Prepare vcpkg
      uses: lukka/run-vcpkg@v7.4
      with:
        vcpkgArguments: protobuf pcre2 --overlay-ports="${{ github.workspace }}\vcpkg-override\ports\pcre2"
        vcpkgGitCommitId: 8dddc6c899ce6fdbeab38b525a31e7f23cb2d5bb
        vcpkgDirectory: ${{ github.workspace }}/vcpkg/
        vcpkgTriplet: x64-windows-static

    # Windows CPU only minimal build
    - name: Build Release # @TODO this is actually a debug build until the ninja generator gets fixed
      uses: lukka/run-cmake@v3
      with:
        buildDirectory: ${{ github.workspace }}/build
        cmakeAppendedArgs: '-G Ninja
          -DCMAKE_BUILD_TYPE="Release"
          -DUSE_WASM_COMPATIBLE_SOURCE="OFF"
          -DUSE_STATIC_LIBS="TRUE" 
          -DCMAKE_CXX_COMPILER_LAUNCHER=${{github.workspace}}\ccache.exe
          -DCMAKE_C_COMPILER_LAUNCHER=${{github.workspace}}\ccache.exe
        '
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
        useVcpkgToolchainFile: true
        cmakeBuildType: Release


    - name: Print versions
      working-directory: build
      run: |
        .\app\bergamot.exe --version
      shell: cmd

    - name: ccache epilog
      run: |-
        ${{github.workspace}}\\ccache.exe -sv # Print current cache stats
